use_frameworks!

platform :ios, '8.0'

target 'HCClangTrace_Example' do
  pod 'HCClangTrace', :path => '../'

  target 'HCClangTrace_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
